services:
  app:
    image: niccoreyes/fhir-webapp  # Use the image from Docker Hub
    container_name: fhir-webapp
    build: .
    ports:
      - "3000:3000"
    environment:
          NODE_ENV: 'production'